[default]
# This is the default value that is written into new pyproject.toml
# files for the `project.requires-python` key
#requires-python = ">= 3.8"
requires-python = ">= 3.9"

# This is the default toolchain that is used
#toolchain = "cpython@3.11.1"

# This is the default build system that is used
#build-system = "hatchling"

# This is the default license that is used
#license = "MIT"
license = "Apache-2.0"

# This sets the default author (overrides the defaults from git).  The
# format here is "Name <email>".
#author = "Full Name <email@address.invalid>"
author = "rcmdnk <rcmdnk@gmail.com>"
authors = "rcmdnk <rcmdnk@gmail.com>"

# The dependency operator to use by default for dependencies.  The options are
# '>=', '~=', and '=='.  The default currently is '>='.  This affects the behavior
# of `rye add`.
#dependency-operator = ">="

[proxy]
# the proxy to use for HTTP (overridden by the http_proxy environment variable)
#http = "http://127.0.0.1:4000"
# the proxy to use for HTTPS (overridden by the https_proxy environment variable)
#https = "http://127.0.0.1:4000"

[behavior]
# When set to true the `managed` flag is always assumed to be true.
#force-rye-managed = false

# Enables global shims when set to `true`.  This means that the installed
# `python` shim will resolve to a Rye managed toolchain even outside of
# virtual environments.
#global-python = false

# When set to `true` enables experimental support of uv as a replacement
# for pip-tools. Learn more about uv here: https://github.com/astral-sh/uv
#use-uv = false
use-uv = true

# Enable or disable automatic `sync` after `add` and `remove`.  This defaults
# to `true` when uv is enabled and `false` otherwise.
#autosync = true

# Marks the managed .venv in a way that cloud based synchronization systems
# like Dropbox and iCloud Files will not upload it.  This defaults to true
# as a .venv in cloud storage typically does not make sense.  Set this to
# `false` to disable this behavior.
#venv-mark-sync-ignore = true

# a array of tables with optional sources.  Same format as in pyproject.toml
[[sources]]
#name = "default"
#url = "http://pypi.org/simple/"

