[settings]
trusted_config_paths = [
    "~/.ghq",
    "~/usr/share/settings",
]

[settings.npm]
bun = true

[tools]
bun = "1.4.0"
go = "1.27.0"
node = "26.7.0"
python = "3.14.7"
ruby = "4.0.6"
rust = "1.97.1"
uv = "0.12.5"

"npm:@github/copilot" = "1.0.80"
"npm:@marp-team/marp-cli" = "4.5.0"
"npm:@openai/codex" = "0.148.0"
"npm:@playwright/mcp" = "0.0.79"
"npm:@upstash/context7-mcp" = "4.0.2"
"npm:chrome-devtools-mcp" = "1.7.0"
"npm:skills" = "1.5.23"
'npm:context-mode' = "1.0.169"

"pipx:apm-cli" = "0.28.0"
"pipx:awslabs.aws-diagram-mcp-server" = "1.0.23"
"pipx:awslabs.aws-pricing-mcp-server" = "1.0.34"
"pipx:browser-use" = "0.13.8"
"pipx:checkov" = "3.3.13"
"pipx:fastmcp" = "3.2.4"
"pipx:mcp-proxy" = "0.12.0"
"pipx:mcp-server-git" = "2026.8.18"
"pipx:poetry" = "2.4.1"
"pipx:prek" = "0.4.14"
"pipx:pre-commit" = "4.6.2"
"github:agavra/tuicr" = "latest"
