[settings]
trusted_config_paths = [
    "~/.ghq",
    "~/usr/share/settings",
]

[settings.npm]
bun = true

[tools]
bun = "1.3.14"
go = "1.26.5"
node = "26.6.0"
python = "3.14.6"
ruby = "4.0.6"
rust = "1.97.1"
uv = "0.12.1"

"npm:@github/copilot" = "1.0.78"
"npm:@marp-team/marp-cli" = "4.5.0"
"npm:@openai/codex" = "0.146.0"
"npm:@playwright/mcp" = "0.0.78"
"npm:@upstash/context7-mcp" = "3.2.5"
"npm:chrome-devtools-mcp" = "1.6.0"
"npm:skills" = "1.5.21"
'npm:context-mode' = "1.0.169"

"pipx:apm-cli" = "0.27.0"
"pipx:awslabs.aws-diagram-mcp-server" = "1.0.23"
"pipx:awslabs.aws-pricing-mcp-server" = "1.0.32"
"pipx:browser-use" = "0.13.7"
"pipx:checkov" = "3.3.9"
"pipx:fastmcp" = "3.2.4"
"pipx:mcp-proxy" = "0.12.0"
"pipx:mcp-server-git" = "2026.7.10"
"pipx:poetry" = "2.4.1"
"pipx:prek" = "0.4.12"
"pipx:pre-commit" = "4.6.1"

