[settings]
trusted_config_paths = [
    "~/.ghq",
]

[settings.npm]
bun = true

[tools]
bun = "1.3.10"
go = "1.26.1"
node = "25.8.1"
python = "3.14.3"
ruby = "4.0.1"
rust = "1.94.0"
uv = "0.10.10"

"npm:@github/copilot" = "1.0.5"
#"npm:@google/gemini-cli" = "0.30.0"
"npm:@marp-team/marp-cli" = "4.3.0"
"npm:@openai/codex" = "0.114.0"
"npm:@playwright/mcp" = "0.0.68"
"npm:@upstash/context7-mcp" = "2.1.4"
"npm:chrome-devtools-mcp" = "0.20.0"
"npm:happy-coder" = "0.13.0"
"npm:skills" = "latest"

"pipx:awslabs.aws-diagram-mcp-server" = "1.0.23"
"pipx:awslabs.aws-pricing-mcp-server" = "1.0.26"
"pipx:checkov" = "3.2.508"
"pipx:fastmcp" = "3.1.1"
"pipx:mcp-proxy" = "0.11.0"
"pipx:mcp-server-git" = "2026.1.14"
"pipx:oraios/serena" = "latest"
"pipx:poetry" = "2.3.2"
